sudo : required
services :
  - docker

before_install :
  - docker build -t bkouhen/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script :
  - docker run bkouhen/multi-docker-client-test npm run test -- --coverage

after_success:
  - docker build -t bkouhen/multi-docker-client ./client
  - docker build -t bkouhen/multi-docker-nginx ./nginx
  - docker build -t bkouhen/multi-docker-server ./server
  - docker build -t bkouhen/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bkouhen/multi-docker-client
  - docker push bkouhen/multi-docker-nginx
  - docker push bkouhen/multi-docker-server
  - docker push bkouhen/multi-docker-worker

deploy:
  provider : elasticbeanstalk
  region : "eu-west-3"
  app : "multi-docker"
  env : "MultiDocker-env"
  bucket_name : "elasticbeanstalk-eu-west-3-146037100981"
  bucket_path : "multi-docker"
  on :
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_SECRET_KEY"
