sudo : required
services :
  - docker

before_install :
  - docker build -t bkouhen/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script :
  - docker run bkouhen/multi-docker-client-test npm run test -- --coverage

after_success:
  - docker build -t bkouhen/multi-docker-client ./client
  - docker build -t bkouhen/multi-docker-nginx ./nginx
  - docker build -t bkouhen/multi-docker-server ./server
  - docker build -t bkouhen/multi-docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bkouhen/multi-docker-client
  - docker push bkouhen/multi-docker-nginx
  - docker push bkouhen/multi-docker-server
  - docker push bkouhen/multi-docker-worker
